apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: microctl
      init:
        command: ["/bin/sh", "-c"]
        args: ["microctl save $MC_APP -t helm -e $MC_ENV -d configs --server http://microconfig-server.default.svc.cluster.local"]
      generate:
        command: [sh, -c]
        args: ["helm template --values configs/values.yaml --values version.yaml $MC_APP app"]